# Generated by Django 4.2.2 on 2024-06-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.TextField(max_length=100),
        ),
    ]
